import 'dart:async';
import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../config.dart';
import '../constants.dart';

/// A single multiple-choice exam question generated by AI.
class ExamQuestion {
  final String question;
  final List<String> choices; // 4 choices, A-D
  final int correctIndex;     // 0-3
  final String explanation;

  const ExamQuestion({
    required this.question,
    required this.choices,
    required this.correctIndex,
    required this.explanation,
  });

  String get correctLetter => ['A', 'B', 'C', 'D'][correctIndex];
}

/// Generates entry-exam questions via OpenAI for the Shadow Arts onboarding.
class AiExamService {
  /// Generates [count] Rank-F level multiple-choice questions for [pathName].
  /// [domain] is the path's domain description (e.g. "Web App Pentest").
  ///
  /// Returns a list of [ExamQuestion]s.
  /// Throws [ExamGenerationException] on failure.
  static Future<List<ExamQuestion>> generateEntryExam({
    required String pathName,
    required String domain,
    int count = 5,
  }) async {
    final systemPrompt = '''You are a cybersecurity instructor creating an entry-level exam.
The student wants to join the "$pathName" path (domain: $domain).

Generate exactly $count multiple-choice questions at beginner (Rank F) difficulty.
These are foundational questions — things a beginner SHOULD know or can reason through.
Do NOT ask about advanced tools or techniques. Focus on concepts, terminology, and basic understanding.

Each question must have exactly 4 choices (A, B, C, D) with exactly 1 correct answer.
Include a brief 1-sentence explanation for why the correct answer is right.

Respond with valid JSON only. No markdown, no code fences.''';

    final http.Response response;
    try {
      response = await http.post(
        Uri.parse(AppConstants.openAiApiUrl),
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer $openAiApiKey',
        },
        body: jsonEncode({
          'model': AppConstants.openAiModel,
          'max_tokens': 2048,
          'messages': [
            {'role': 'system', 'content': systemPrompt},
            {'role': 'user', 'content': 'Generate the entry exam now.'},
          ],
          'response_format': {
            'type': 'json_schema',
            'json_schema': {
              'name': 'entry_exam',
              'strict': true,
              'schema': {
                'type': 'object',
                'properties': {
                  'questions': {
                    'type': 'array',
                    'items': {
                      'type': 'object',
                      'properties': {
                        'question': {'type': 'string'},
                        'choices': {
                          'type': 'array',
                          'items': {'type': 'string'},
                        },
                        'correct_index': {'type': 'integer'},
                        'explanation': {'type': 'string'},
                      },
                      'required': [
                        'question',
                        'choices',
                        'correct_index',
                        'explanation',
                      ],
                      'additionalProperties': false,
                    },
                  },
                },
                'required': ['questions'],
                'additionalProperties': false,
              },
            },
          },
        }),
      ).timeout(const Duration(seconds: 30));
    } on TimeoutException {
      throw ExamGenerationException(
        'The exam scroll took too long to materialize. Try again.',
      );
    }

    // Debug: print API response details to console
    debugPrint('[ExamService] Status: ${response.statusCode}');
    debugPrint('[ExamService] Body: ${response.body}');

    if (response.statusCode == 429) {
      throw ExamGenerationException(
        'The sect elders are busy. Rest and return shortly.',
      );
    }
    if (response.statusCode != 200) {
      throw ExamGenerationException(
        'The exam could not be prepared. Status ${response.statusCode}: ${response.body}',
      );
    }

    late Map<String, dynamic> data;
    try {
      data = jsonDecode(response.body) as Map<String, dynamic>;
    } catch (_) {
      throw ExamGenerationException('The exam scroll was unreadable. Try again.');
    }

    final choices = data['choices'] as List<dynamic>?;
    if (choices == null || choices.isEmpty) {
      throw ExamGenerationException('The exam scroll was empty. Try again.');
    }

    final raw = (choices.first['message']['content'] as String).trim();

    // Strip any accidental code fences
    String cleaned = raw;
    if (cleaned.startsWith('```')) {
      cleaned = cleaned
          .replaceAll(RegExp(r'```json?\s*'), '')
          .replaceAll('```', '')
          .trim();
    }

    try {
      final json = jsonDecode(cleaned) as Map<String, dynamic>;
      final questions = (json['questions'] as List<dynamic>).map((q) {
        final m = q as Map<String, dynamic>;
        final choiceList =
            (m['choices'] as List<dynamic>).map((c) => c as String).toList();
        return ExamQuestion(
          question: m['question'] as String,
          choices: choiceList,
          correctIndex: (m['correct_index'] as num).toInt(),
          explanation: m['explanation'] as String,
        );
      }).toList();

      if (questions.length < count) {
        throw ExamGenerationException(
          'The exam was incomplete. Try again.',
        );
      }

      return questions.take(count).toList();
    } catch (e) {
      if (e is ExamGenerationException) rethrow;
      throw ExamGenerationException('The exam scroll was corrupted. Try again.');
    }
  }
}

class ExamGenerationException implements Exception {
  final String message;
  const ExamGenerationException(this.message);
  @override
  String toString() => message;
}
